// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7IJeqSgY_6QAfOxq1vD_5xG1tJbd7qGo',
    appId: '1:368393241409:web:45a5af960c1d21237957c0',
    messagingSenderId: '368393241409',
    projectId: 'tide-pomodoro',
    authDomain: 'tide-pomodoro.firebaseapp.com',
    storageBucket: 'tide-pomodoro.firebasestorage.app',
    measurementId: 'G-HJN675ZP85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD26WAs1FqiDeCONa_8fonyJer8lc3vKuw',
    appId: '1:368393241409:android:7e0a6b2de1454f897957c0',
    messagingSenderId: '368393241409',
    projectId: 'tide-pomodoro',
    storageBucket: 'tide-pomodoro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJF1RWcHUOOhsr5Eqh6GvXUskTtkbrSXY',
    appId: '1:368393241409:ios:c8986c52b1771c447957c0',
    messagingSenderId: '368393241409',
    projectId: 'tide-pomodoro',
    storageBucket: 'tide-pomodoro.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJF1RWcHUOOhsr5Eqh6GvXUskTtkbrSXY',
    appId: '1:368393241409:ios:c8986c52b1771c447957c0',
    messagingSenderId: '368393241409',
    projectId: 'tide-pomodoro',
    storageBucket: 'tide-pomodoro.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroTimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7IJeqSgY_6QAfOxq1vD_5xG1tJbd7qGo',
    appId: '1:368393241409:web:ae71873f2fd1bdec7957c0',
    messagingSenderId: '368393241409',
    projectId: 'tide-pomodoro',
    authDomain: 'tide-pomodoro.firebaseapp.com',
    storageBucket: 'tide-pomodoro.firebasestorage.app',
    measurementId: 'G-LTL2WLK00Q',
  );
}
